version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:15.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=magnetissimo
    networks:
      - magnetissimo
    volumes:
      - "pgdata:/var/lib/postgresql/data"
  magnetissimo:
    container_name: magnetissimo
    build: https://github.com/sergiotapia/magnetissimo.git
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/magnetissimo
      # You should change this to a random 32 to 64 character string
      # You can run: openssl rand -base64 48
      # or: mix phx.gen.secret
      # - SECRET_KEY_BASE=
    networks:
      - magnetissimo
    ports:
      - "4000:4000/tcp"
    depends_on:
      - postgres

networks:
  magnetissimo:

volumes:
  pgdata:
    driver: local
